version: "3.8"
services:
  collector:
    build:
      context: ./collector
    image: data_collector
    container_name: collector
  analyzer:
    build:
      context: ./analyzer
    image: data_analyzer
    container_name: analyzer
  web:
    build:
      context: ./web
    image: web_app
    container_name: web_app
    ports:
      - "5000:5000"